name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run rustfmt
      run: |
        rustup component add rustfmt \
        && cargo fmt -- --check
    - name: Run Clippy
      run: |
        rustup component add clippy \
        && cargo clippy
